config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about', to: 'homes#about', as: 'about'

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
  resources :post_images, only: [:new, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :profile_images, dependent: :destroy
  has_many :books
  has_one_attached :profile_image

   def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller? 

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email]) 
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    @user = current_user
  
    if @book.save
     redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      render :edit
    end
  end



  def destroy
    @book = Book.find(params[:id])
    if @book.user == current_user
     @book.destroy
    end
      redirect_to books_path
  end
    

 private

 def book_params
   params.require(:book).permit(:title, :body)
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:about]
  
  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new    
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_path(current_user) unless current_user == @user
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
            flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit 
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_info.html.erb
<div class="col-md-3">
 <h2>User info</h2>
  <%= link_to user_path(@user) do %>
   <% if @user.profile_image.attached? %>
    <%= image_tag @user.profile_image, size: "100x100" %>
   <% else %>
    <%= image_tag 'no_image.jpg', size: "100x100", alt: "No Image" %>
   <% end %>
  <% end %>

 <table class="table">
  <tbody>
   <tr>
    <th>name</th>
    <th><%= @user.name %></th>
   </tr>
   <tr>
    <th>introduction</th>
    <th><%= @user.introduction %></th>
   </tr>
  </tbody>
 </table>

 <div class="row">
  <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
   <i class="fa-solid fa-user-gear"></i>
  <% end %>
 </div>

  <h2 class="mt-3">New book</h2>
   <%= form_with(model: Book.new, local: true, data: { turbo: false }) do |f| %>
    <div class="form-group">
     <%= f.label :title, "Title", class: "form-label" %>
     <%= f.text_field :title, class: "form-control" %>
    </div>
     <div class="form-group">
     <%= f.label :body, "Opinion",class: "form-label" %>
     <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
     <%= f.submit 'Create Book', class: "btn btn-success", data: { disable_with: "Create Book" }  %>
    </div>
   <% end %>
</div>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<maim>
 <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h1>Editing Book</h1>

     <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
     <ul>
       <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   <% end %>

      <%= form_with model: @book do |f| %>
       <div class="form-group">
       <%= f.label :title, "Title", class: "form-label" %>  
       <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
       <%= f.label :opinion, "Opinion", class: "form-label" %>  
       <%= f.text_area :body, class: "form-control"%>
      </div>

       <div class="form-group">
        <%= f.submit 'Update Book', class: "btn btn-success", data: { disable_with: "Create Book" }  %>
       </div>
       <% end %>

        <%= link_to "Show", book_path(@book.id) %>
        |
        <%= link_to "Back", books_path %>
    </div>
   </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
<p id="notice"></p>
 <div class="container px-5 px-sm-0">

  <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
     <ul>
     <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
   </ul>
  <% end %>

  <div class="row">
   <%= render 'book_info', book: @book %>

     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
        </tr>
       </thead>
      
       <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
             <%= link_to user_path(book.user) do %>
              <% if book.user.profile_image.attached? %>
               <%= image_tag book.user.profile_image.variant(resize: "80x80"), alt: "User Image" %>
              <% else %>
               <%= image_tag 'no_image.jpg', size: "80x80", alt: "No Image" %>
              <% end %>
             <% end %>
            </td>
            <td>
             <%= link_to book.title, book_path(book), class: "book-link" %>
            </td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
       </tbody>
      </table>
     </div>
  </div>
 </div>
</main>

app/views/books/show.html.erb
<main>
<p id="notice"></p>
<div class="container">
 <div class="row">

   <%= render 'book_info', book: @book %>

  <div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <tr>
       <td>
        <%= link_to user_path(@book.user) do %>
         <% if @book.user.profile_image.attached? %>
          <%= image_tag @book.user.profile_image.variant(resize: "100x100"), alt: "User Image" %>
         <% else %>
          <%= image_tag 'no_image.jpg', size: "100x100", alt: "No Image" %>
         <% end %>
        <% end %>
       <br>
        <%= link_to @book.user.name, user_path(@book.user) %>
       </td>
       <td>
       <%= link_to @book.title, book_path(@book), class: "book-link" %>
       </td>
       <td><%= @book.body %></td>

        <% if @book.user == current_user %>
         <td>
          <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
         </td>
         <td>
          <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "本当に消しますか？" } %>
         </td>
        <% end %>
       </tr>
    </tbody>
  </table>
</div>

   
   

app/views/homes/about.html.erb
 <main>
  <p id="notice"></p>
   <div class="container">
    <div class="row">
     <h1 class="px-3 mx-auto">Welcome to
     <i class="fa-solid fa-book"></i><strong>Bookers</strong>!</h1>
     </div>
    </div>
   </div>
 </main>

app/views/homes/top.html.erb
 <main>
  <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
     <h1>welcome to 
     <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
     <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
     <p>you can share and exchange your opinions , inpressions , and emotions</p>
     <p>about various books!</p>

     <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
       <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
      </div>
      <div class="row">
       <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
      </div>
     </div>
    </div>
   </div>
  </div>
 </main>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Bookers2Ver2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/91aa0a6112.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-0">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
  
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
              <% if user_signed_in? %>
              <li>
                <a class="nav-link text-light" href="<%= user_path(current_user) %>">
                  <i class="fa-solid fa-house"></i> Home
                </a>
              </li>
                <li>
                  <a class="nav-link text-light" href="/users">
                    <i class="fa-solid fa-users"></i> Users
                  </a>
                </li>
                <li>
                  <a class="nav-link text-light" href="/books">
                    <i class="fa-solid fa-book-open"></i> Books
                  </a>
                </li>
                <li>

                <li>
                 <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light nav-item" do %>
                  <i class="fa-solid fa-right-from-bracket"></i> Log out
                 <% end %>
                </li>           
                <% else %>
     
              <li>
                <a class="nav-link text-light" href="/">
                  <i class="fa-solid fa-house"></i> Home
                </a>
              </li>

                <li>
                  <a class="nav-link text-light" href="/home/about">
                    <i class="fa-solid fa-link"></i> About
                  </a>
                </li>
                <li>
                  <a class="nav-link text-light" href="/users/sign_up">
                    <i class="fa-solid fa-user-plus"></i> Sign up
                  </a>
                </li>
                <li>
                  <a class="nav-link text-light" href="/users/sign_in">
                    <i class="fa-solid fa-right-to-bracket"></i> Log in
                  </a>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  </body>

  <main> 
   <% flash.each do |message_type, message| %>
     <div class="flash-message <%= message_type %>"><%= message %></div>
   <% end %>
   <%= yield %>
  </main>

  <footer>
  <div class="container mt-5">
   <div class="row">
     <div class="mx-auto">
       <p>CopyRight Infratop.inc</p>
   </div>
  </div>
 </footer>
</html>

app/views/users/_user_info_and_new_book.html.erb
<div class="col-md-3">
 <h2>User info</h2>
  <% if @user.profile_image.attached? %>
   <%= image_tag @user.profile_image, size: "100x100" %>
  <% else %>
   <%= image_tag 'no_image.jpg', size: "100x100", alt: "No Image" %>
  <% end %>

  <table class="table">
   <tbody>
    <tr>
     <th>name</th>
     <th><%= @user.name %></th>
    </tr>
    <tr>
     <th>introduction</th>
     <th><%= @user.introduction %></th>
    </tr>
   </tbody>
  </table>

  <div class="row">
   <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fa-solid fa-user-gear"></i>
   <% end %>
  </div>


  <h2 class="mt-3">New book</h2>
  <%= form_with(model: Book.new, local: true, data: { turbo: false }) do |f| %>
  <div class="form-group">
   <%= f.label :title, "Title", class: "form-label" %>  
   <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
   <%= f.label :body, "Opinion", class: "form-label" %>  
   <%= f.text_area :body, class: "form-control" %>
  </div>
   <div class="form-group">
   <%= f.submit 'Create Book', class: "btn btn-success", data: { disable_with: "Create Book" }  %>
  </div>
 <% end %>
</div>

app/views/users/edit.html.erb
<main>
 <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2>User info</h2>

     <% if @user.errors.any? %>
   <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
     <ul>
       <% @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   <% end %>


     <%= form_with model: @user, url: user_path(@user), method: :patch do |f| %>
  
     <div class="form-group">
      <%= f.label :name, "Name", class: "form-label" %>  
       <%= f.text_field :name, class: "form-control" %>
	   </div>

     <div class="form-group">
     <%= f.label :profile_image, "Profile Image", class: "form-label" %>  
      <div>
       <%= f.file_field :profile_image, accept: "image/*" %>
      </div>
     </div>

     <div class="form-group">
     <%= f.label :introduction, "Introduction", class: "form-label" %>  
      <%= f.text_area :introduction, class: "form-control" %>
	   </div>

     <div class="form-group">
      <%= f.submit 'Update User', class: "btn btn-secondary" %>
     </div>
    <% end %>
    </div>
   </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
 <p id="notice"></p>
 <div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'user_info_and_new_book', user: @user, book: Book.new %>

    <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
     <table class="table table-hover table-inverse">
     <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
     </thead>
     <tbody>
     <% @users.each do |user| %>
      <tr>
        <td>
         <%= link_to user_path(user) do %>
          <% if user.profile_image.attached? %>
           <%= image_tag user.profile_image.variant(resize: "80x80"), alt: "User Image" %>
          <% else %>
           <%= image_tag "no_image.jpg", size: "80x80", alt: "No Image" %>
          <% end %>
         <% end %>
        </td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
     <% end %>
     </tbody>
     </table>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
    <div class="container px-5 px-sm-0">
     <div class="row">
      <%= render 'user_info_and_new_book', user: @user, book: @book %>

        <div class="col-md-8 offset-md-1">
         <h2>Books</h2>
         <table class="table table-hover table-inverse">
          <thead>
           <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
           </tr>
          </thead>
          <tbody>
           <% @books.each do |book| %>
            <tr>
            <th>
             <%= link_to book.user do %>
              <% if book.user.profile_image.attached? %>
               <%= image_tag book.user.profile_image.variant(resize: "50x50"), alt: "User Image" %>
              <% else %>
               <%= image_tag 'no_image.jpg', size: "80x80", alt: "No Image" %>
              <% end %>
             <% end %>
            </th>
            <th> <%= link_to book.title, book_path(book) %></th>
            <th><%= book.body %></th>
            <th colspan="3"></th>
           </tr>
           <% end %>
          </tbody>
         </table>
        </div>
       </div>
     </div>
    </div>
</main>